### ISSUE TITLE
Selecting the 'Managed Services for Google Platform' box from support landing page redirects to existing site 

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#119]
Selecting the 'Managed Services for Google Platform' box on <https://docs-support-how-to.netlify.app>  redirects to <https://developer.rackspace.com/docs/fanatical-support-gcp/>

**Comment by codebyravi** [comment]
Fixed.

**Comment by Sterling463** [comment]
This issue still exists. I tested it on Safari and the behavior is the same

**Comment by Sterling463** [comment]
Not an issue
