### ISSUE TITLE
No articles displayed in all articles section

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#194]
https://docs.rackspace.com/support/how-to/all

**Comment by codebyravi** [comment]
Fixed.

**Comment by Sterling463** [comment]
This still doesn't show anything but I am not sure if this is a URL that we need

**Comment by WilliamLoy** [comment]
@codebyravi @Sterling463 I am not sure we ever had this working on the legacy site
