### ISSUE TITLE
Bug: Bullet alignment

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/support-how-to#38]
Bulleted lists are indented too far to the left:

![Screen Shot 2020-08-13 at 3 51 15 PM](https://user-images.githubusercontent.com/12717324/90185795-cdffd480-dd7c-11ea-950e-75ae721a34b3.png)

**Comment by codebyravi** [comment]
fixed

**Comment by stephamon** [comment]
@codebyravi well the alignment looks fine, but now the bullets are gone 😄 

<img width="928" alt="Screen Shot 2020-08-18 at 8 09 27 AM" src="https://user-images.githubusercontent.com/12717324/90516813-27c02000-e12a-11ea-9a5d-02b1c64306fc.png">

**Comment by stephamon** [comment]
Hey @codebyravi I'm still not seeing the bullets on this page: https://docs-support-how-to.netlify.app/support/how-to/account-management

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 1 29 02 PM](https://user-images.githubusercontent.com/1606969/91224434-f241a680-e6d6-11ea-9677-449cb656aed8.png)
